name: API Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run tests daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      test_group:
        description: 'Test group to run'
        required: false
        default: 'regression'
        type: choice
        options:
          - smoke
          - regression
          - all

env:
  JAVA_VERSION: '17'
  MAVEN_OPTS: '-Xmx2048m'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-group: [smoke, regression]
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: maven

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Install dependencies
      run: mvn clean compile test-compile

    - name: Run health check
      run: |
        echo "Checking API health..."
        curl -f https://restful-booker.herokuapp.com/ping || echo "API health check failed"

    - name: Run smoke tests
      if: matrix.test-group == 'smoke' || github.event.inputs.test_group == 'smoke'
      run: mvn test -Dgroups=smoke
      continue-on-error: true

    - name: Run regression tests
      if: matrix.test-group == 'regression' || github.event.inputs.test_group == 'regression'
      run: mvn test -Dgroups=regression
      continue-on-error: true

    - name: Run all tests
      if: github.event.inputs.test_group == 'all'
      run: mvn test
      continue-on-error: true

    - name: Generate Allure Report
      if: always()
      run: mvn allure:report

    - name: Upload Allure Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: allure-results-${{ matrix.test-group }}
        path: target/allure-results/
        retention-days: 30

    - name: Upload Test Logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-logs-${{ matrix.test-group }}
        path: target/logs/
        retention-days: 7

    - name: Upload Surefire Reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: surefire-reports-${{ matrix.test-group }}
        path: target/surefire-reports/
        retention-days: 7

  allure-report:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Merge Allure Results
      run: |
        mkdir -p merged-results
        find artifacts -name "allure-results*" -type d -exec cp -r {}/* merged-results/ \; 2>/dev/null || true

    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: merged-results
        allure_report: allure-report
        gh_pages: gh-pages
        allure_history: allure-history

    - name: Deploy to GitHub Pages
      if: always() && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-history
        destination_dir: allure-report

  notify:
    runs-on: ubuntu-latest
    needs: [test, allure-report]
    if: always()
    
    steps:
    - name: Test Results Summary
      run: |
        echo "## Test Execution Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Repository:** ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Workflow:** ${{ github.workflow }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Test Status:** ${{ needs.test.result }}" >> $GITHUB_STEP_SUMMARY
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "- **Allure Report:** [View Report](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/allure-report/)" >> $GITHUB_STEP_SUMMARY
        fi


